### ISSUE TITLE
Your theme's demo is not working on the Hugo Themes website

### ISSUE THREAD

**Issue by digitalcraftsman** [TiTi/hurock#4]
Hello @TiTi,

the maintainers of the Hugo theme site (which includes me) started a "spring cleaning" in which we began to remove themes that are unmaintained or whose demo is broken. The theme itself builds fine, however the content folder in this repo isn't populated with content that would be seen on the [homepage of your theme's demo](https://themes.gohugo.io/theme/hurock/), which causes the page to remain nearly empty. See https://github.com/gohugoio/hugoThemes/pull/489 for more information.

It would be great if you could additional content for the demo. Once this issue is fixed we're happy to add hurock again.

**Comment by TiTi** [comment]
Hello,
Thank you for noticing me.
Yeah there were no sample article because: 
* Sections really depends on your content. On my personnal blog its "posts" and "links" but maybe you want something else
* The point was to start right away with it (no clean up needed)

But I guess I could add a handeful of article to showcase something.
Le me try something...

**Comment by TiTi** [comment]
Ok I did something with 44c18a6a3b494f6f010a52c1b65903755850ba18

However I didn't had time to test it with the Hugo Themes website Build Script (./generateThemeSite.sh) because I'm on a Windows system and it's getting late.

Hopefully I'll try that tomorrow.

**Comment by TiTi** [comment]
Looks good to me @digitalcraftsman
Should I create a new issue to re-add the theme?

**Comment by digitalcraftsman** [comment]
Thank you @TiTi for fixing the issue so quick. Your theme has already been (re)added in https://github.com/gohugoio/hugoThemes/commit/aaee4830d58f80bb9ab71c7e3536435c878c1be4 :wink:
